In [1]:
import numpy as np

# 1D Array

In [2]:
arr = np.array([1,2,3,4,5,6,7,8])
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
arr = np.array([1,2,3,4], dtype = np.int32) #np.int64, np.float32, np.float64
arr

array([1, 2, 3, 4], dtype=int32)

In [4]:
#NumPy arrays can contain only homogeneous datatypes, values will be upcast if the types do not match:
np.array([1,2,3.0,4.0], dtype = np.int64)
#Here, NumPy has upcast float values to int values.

array([1, 2, 3, 4])

# 2D Array

In [5]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array of zeros

In [6]:
np.zeros(3, dtype = np.int32) #1D array with 3 elements equal to zero

array([0, 0, 0], dtype=int32)

In [7]:
np.zeros((3,3)) #2D array 3*3 matrix, all elements equal to zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones(4) #1D array with 4 elements equal to one

array([1., 1., 1., 1.])

In [9]:
np.ones((3,3), dtype = np.int64) #2D array 3*3 matrix, all elements equal to zero

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Random numbers in ndarrays

In [10]:
np.random.rand(2,2) #Here dtype cannot be done

array([[0.54059725, 0.36314131],
       [0.32693543, 0.48211035]])

### An array of your choice


In [11]:
np.full((2,2), 4) #A 2*2 matrix with all elements equal to 4

array([[4, 4],
       [4, 4]])

### Identity Matrix

In [12]:
np.eye(3) # Can do dtype here

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

NumPy gives you the flexibility to change the diagonal along which the values have to be 1's. You can either move it below the main diagonal or above it.

In [13]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [14]:
np.eye(3, k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [16]:
np.eye(3, k=2)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Slicing a Array

In [17]:
arr = np.array(([1,2,3],
                [4,5,6],
                [7,8,9]))

In [18]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
b = arr[0:1, :]

In [20]:
b

array([[1, 2, 3]])

In [21]:
b = arr[0:2, 0:2]
b

array([[1, 2],
       [4, 5]])

In [22]:
b

array([[1, 2],
       [4, 5]])