In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5], np.int32) #Can do np.int8/16/32/62
                                      #Or np.float32/64

In [3]:
type(arr)

numpy.ndarray

In [4]:
myarr = np.array([[1,3,2,6,7,4]]) #2D array

In [5]:
myarr[0,2]

2

In [6]:
myarr.dtype #Default dtype is int64

dtype('int64')

In [7]:
myarr.size

6

In [8]:
myarr.shape

(1, 6)

In [9]:
myarr[0,1] = 10 #Changing value of element (0,1)

In [10]:
myarr

array([[ 1, 10,  2,  6,  7,  4]])

## Making numpy array from list/tuple

In [11]:
list1 = [1,22,3,4,59,6,10]

In [12]:
arr1 = np.array(list1) #1D Array
arr1

array([ 1, 22,  3,  4, 59,  6, 10])

In [13]:
arr1.dtype #As my system is 64bit so default dtype is 64 bit

dtype('int64')

In [14]:
list2 = [[1,2,3], [2,3,11], [34,5,21]]

In [15]:
arr2 = np.array(list2, np.int16) #2D Array
arr2

array([[ 1,  2,  3],
       [ 2,  3, 11],
       [34,  5, 21]], dtype=int16)

In [16]:
arr2.dtype #Here i specified the dtype to be int16

dtype('int16')

In [17]:
tuple1 = (1,32,45,23,46)

In [18]:
arr3 = np.array(tuple1, np.float32)

In [19]:
arr3.dtype

dtype('float32')

In [20]:
dict1 = {1,2,45}

In [21]:
np.array(dict1) #dtype of the array created using dict is object, which is not so recommended

array({1, 2, 45}, dtype=object)

## Intrinsic numpy array creation objects

In [22]:
zeros = np.zeros((2,2))
zeros

array([[0., 0.],
       [0., 0.]])

In [23]:
zeros.dtype

dtype('float64')

In [24]:
zeros = np.zeros((2,2), np.int32)
zeros

array([[0, 0],
       [0, 0]], dtype=int32)

In [25]:
rng = np.arange(11) #creates numpy array from 0 to n-1
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
lspace = np.linspace(1, 50, 10) # from 1 to 50 divided in to give equal spaced 10 elements
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [27]:
lspace.size

10

In [28]:
emp = np.empty((3,3)) #Gives a numpy array of 3*3 size with all random values, we can assign the value as per our req.
emp

array([[ 2.60605835e-31, -5.21211670e-31,  1.30302917e-31],
       [-5.21211670e-31,  1.13363538e-30, -3.51817877e-31],
       [ 1.30302917e-31, -3.51817877e-31,  2.01969522e-31]])

In [29]:
emp_like = np.empty_like(lspace)
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

Identity Matrix

In [30]:
ide = np.identity(5) # Gives identity matrix of 5*5
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
ide.shape

(5, 5)

In [32]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
arr.size

99

In [34]:
arr.reshape(3, 33) # As arr is of 99 size, so if we reshape it then n*m = 99
                  # eg: 3*33 = 99, 9*11 = 99 etc..

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [35]:
arr = arr.reshape(9, 11)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
       [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [36]:
arr.shape

(9, 11)

To flatten

In [37]:
arr = arr.flatten() # Can also use arr = arr.flatten()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
arr.shape

(99,)

In [39]:
ar = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
ar.sum(axis = 0) #Sum in vertical direction
                 #Axis = 0 is for rows

array([12, 15, 18])

In [41]:
ar.sum(axis = 1) #Sum in horizontal direction
                 #Axis = 1 is for columns

array([ 6, 15, 24])

Transpose

In [42]:
ar.T # To change the original array ar = ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [43]:
ar.flat #Returns as an iterator

In [44]:
for item in ar.flat: 
    print(item)

1
2
3
4
5
6
7
8
9


In [45]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
ar.ndim #As ar is an 2D array

2

In [47]:
priya = np.array([[[[1,2,3,4]]]])

In [48]:
priya.ndim #As priya is a 4D array

4

In [49]:
ar.nbytes #Tells how much bytes is comsumed by array

72

In [50]:
one = np.array([21,34,22,100,34,12,3,4,5])

In [51]:
max_index = one.argmax() #returns the index of biggest element

In [52]:
one[max_index]

100

In [53]:
one.argsort() #Return the index order needed to sort the array

array([6, 7, 8, 5, 0, 2, 1, 4, 3])

In [54]:
priya = np.array([[1,56,32],
                  [99,2,7],
                  [3,50,77]])
priya

array([[ 1, 56, 32],
       [99,  2,  7],
       [ 3, 50, 77]])

In [55]:
priya.argmin() #It first flattens the array and then tells the index of smallest element

0

In [56]:
priya.argmax() #It first flattens the array and then tells the index of largest element

3

In [57]:
priya.argmin(axis = 0) #axis = 0 for rows
                       #Vertical

array([0, 1, 1])

In [58]:
priya.argmin(axis = 1)

array([0, 1, 0])

In [59]:
priya.argmax(axis = 0)

array([1, 0, 2])

In [60]:
priya.argmax(axis = 1)

array([1, 0, 2])

In [61]:
priya

array([[ 1, 56, 32],
       [99,  2,  7],
       [ 3, 50, 77]])

In [62]:
priya.argsort(axis = 0)

array([[0, 1, 1],
       [2, 2, 0],
       [1, 0, 2]])

In [63]:
priya.argsort(axis = 1)

array([[0, 2, 1],
       [1, 2, 0],
       [0, 1, 2]])

In [64]:
ar1 = np.array([[1,1,1],
                [2,2,2], 
                [3,3,3]])

In [65]:
ar2 = np.array([[10,10,10],
                [20,20,20], 
                [30,30,30]])

In [66]:
ar1 + ar2 #If we did this in list then it would have concatenated the list not added it.

array([[11, 11, 11],
       [22, 22, 22],
       [33, 33, 33]])

In [67]:
ar1 * ar2 #This is not matrix multiplcation, it is corresponding element multiplication

array([[10, 10, 10],
       [40, 40, 40],
       [90, 90, 90]])

In [68]:
ar.max()

9

In [69]:
ar.min()

1

In [70]:
np.sqrt(ar1)

array([[1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.41421356],
       [1.73205081, 1.73205081, 1.73205081]])

In [71]:
np.power(ar1, 2)

array([[1, 1, 1],
       [4, 4, 4],
       [9, 9, 9]])

In [72]:
np.where(ar1>5)

(array([], dtype=int64), array([], dtype=int64))

## Numpy array and python array size comparison

In [73]:
import sys

In [74]:
py_arr = [0,4,55,2]

In [75]:
sys.getsizeof(1) * len(py_arr)

112

In [76]:
np_arr = np.array([0,4,55,2])

In [77]:
np_arr.itemsize * np_arr.size

32

Convert Numpy array to list

In [78]:
np_arr.tolist()

[0, 4, 55, 2]